[package]
name = "endo"
version = "0.1.0"
authors = ["Delton Ding <dsh0416@gmail.com>"]

[lib]
name = "endo"
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
lalrpop = "0.16.3"

[dependencies]
serde_json = "1.0"
lalrpop-util = "0.16.3"
regex = "0.2.1"
