PROGRAM  ::= COMPSTMT
COMPSTMT ::= ";" | "\n"

EXPR     ::= MLHS = MRHS
         ::= return CALL_ARGS
         ::= EXPR and EXPR
         ::= EXPR or EXPR
         ::= not EXPR
         ::= COMMAND
         ::= ! COMMAND
         ::= ARG
